### ISSUE TITLE
Семантическая ошибка в CreateNegotiationForm.vue

### ISSUE THREAD

**Issue by PavelMeld** [k-vasiliev/hh-backend-homework#10]
В форме добавления отзыва `CreateNegotiationForm.vue` осталась копи-паста от формы `CreateUserForm.vue`

https://github.com/k-vasiliev/hh-backend-homework/blob/d8bc4697db3987d228cc2343dcd281491becc449/frontend/src/components/CreateNegotiationForm.vue#L20

https://github.com/k-vasiliev/hh-backend-homework/blob/d8bc4697db3987d228cc2343dcd281491becc449/frontend/src/components/CreateNegotiationForm.vue#L40

https://github.com/k-vasiliev/hh-backend-homework/blob/d8bc4697db3987d228cc2343dcd281491becc449/frontend/src/components/CreateNegotiationForm.vue#L58

**Comment by k-vasiliev** [comment]
Исправлено
